---
title: "modeling"
format: html
---

```{r}
library(readr)
library(tidyverse)
library(dplyr)
```

```{r}
acc_games <- read.csv("data/acc_games_cleaned.csv")
acc_teams_stats <- read.csv("data/combined_acc.csv") |>
  mutate(opponent = TeamName)
predict <- read.csv("data/2026_predict.csv") 
```

```{r}
acc_games <- acc_games |>
  mutate(Season = season + 1,
         TeamName = team) |>
  select(-season, -team) |>
  filter(Season != 2021) |>
  mutate(
    TeamName = case_when(
      TeamName == "Cal" ~ "California",
      TeamName == "UNC" ~ "North Carolina",
      TeamName == "Florida State" ~ "Florida St.",
      TeamName == "UVA" ~ "Virginia",
      TeamName == "Miami" ~ "Miami FL",
      TeamName == "Pitt" ~ "Pittsburgh",
      TeamName == "NC State" ~ "N.C. State",
      TRUE ~ TeamName
    )
  ) |>
  mutate(
    opponent = case_when(
      opponent == "Cal" ~ "California",
      opponent == "UNC" ~ "North Carolina",
      opponent == "Florida State" ~ "Florida St.",
      opponent == "UVA" ~ "Virginia",
      opponent == "Miami" ~ "Miami FL",
      opponent == "Pitt" ~ "Pittsburgh",
      opponent == "NC State" ~ "N.C. State",
      TRUE ~ opponent)
    )
```

```{r}
merged_data <- left_join(
  acc_games,
  acc_teams_stats,
  by = c("TeamName", "Season")
) |>
  drop_na() |>
  rename("home_eFGPct" = "eFGPct",
         "home_TOPct" = "TOPct",
         "home_ORPct" = "ORPct",
         "home_FTRate" = "FTRate",
         "opponent" = "opponent.x"
         ) |>
  select(-opponent.y)


```

```{r}
merged_all <- left_join(
  merged_data,
  acc_teams_stats,
  by = c("opponent", "Season")
) |>
  rename("away_eFGPct" = "eFGPct",
         "away_TOPct" = "TOPct",
         "away_ORPct" = "ORPct",
         "away_FTRate" = "FTRate",
         "TeamName" = "TeamName.x"
         ) |>
  mutate(
    diff_eFGPct = home_eFGPct - away_eFGPct,
    diff_TOPct = home_TOPct - away_TOPct,
    diff_ORPct = home_ORPct - away_ORPct,
    diff_FTRate = home_FTRate - away_FTRate
  ) |>
  select(
    TeamName, opponent, location, team_score, opp_score, diff, Season, diff_eFGPct, diff_TOPct, diff_ORPct, diff_FTRate
  )|>
  relocate(TeamName, opponent, Season) |>
  mutate(home = if_else(location == "N", 0, 1))
```




```{r}
model_1 <- lm(diff ~ diff_eFGPct + diff_TOPct + diff_ORPct + diff_FTRate + home, data = merged_all)

summary(model_1)
```

```{r}

predicted <- predict(model_1, newdata = merged_all)

merged_w_predicted <- merged_all |>
  mutate(predicted = predict(model_1, newdata = merged_all))
```


```{r}
ggplot(merged_w_predicted, aes(x = predicted, y = diff)) +
         geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
lm <- lm(diff ~ predicted, data = merged_w_predicted)

coef(lm)
```

```{r}
games_2026 <- read.csv("data/2026_predict.csv")
```

```{r}
games_2026 <- games_2026 |>
  mutate(
         TeamName = Home,
         opponent = Away) |>
  select(-Home, -Away) |>
  mutate(
    TeamName = case_when(
      TeamName == "Cal" ~ "California",
      TeamName == "UNC" ~ "North Carolina",
      TeamName == "Florida State" ~ "Florida St.",
      TeamName == "UVA" ~ "Virginia",
      TeamName == "Miami" ~ "Miami FL",
      TeamName == "Pitt" ~ "Pittsburgh",
      TeamName == "NC State" ~ "N.C. State",
      TRUE ~ TeamName
    )
  ) |>
  mutate(
    opponent = case_when(
      opponent == "Cal" ~ "California",
      opponent == "UNC" ~ "North Carolina",
      opponent == "Florida State" ~ "Florida St.",
      opponent == "UVA" ~ "Virginia",
      opponent == "Miami" ~ "Miami FL",
      opponent == "Pitt" ~ "Pittsburgh",
      opponent == "NC State" ~ "N.C. State",
      TRUE ~ opponent)
    ) |>
  mutate(Season = 2026,
         location = "H") |>
  select(TeamName, opponent, Season, location)
```

```{r}
merged_data_2026 <- left_join(
  games_2026,
  acc_teams_stats,
  by = c("TeamName", "Season")
) |>
  drop_na() |>
  rename("home_eFGPct" = "eFGPct",
         "home_TOPct" = "TOPct",
         "home_ORPct" = "ORPct",
         "home_FTRate" = "FTRate",
         "opponent" = "opponent.x"
         ) |>
  select(-opponent.y)

```

```{r}
merged_all_2026 <- left_join(
  merged_data_2026,
  acc_teams_stats,
  by = c("opponent", "Season")
) |>
  rename("away_eFGPct" = "eFGPct",
         "away_TOPct" = "TOPct",
         "away_ORPct" = "ORPct",
         "away_FTRate" = "FTRate",
         "TeamName" = "TeamName.x"
         ) |>
  mutate(
    diff_eFGPct = home_eFGPct - away_eFGPct,
    diff_TOPct = home_TOPct - away_TOPct,
    diff_ORPct = home_ORPct - away_ORPct,
    diff_FTRate = home_FTRate - away_FTRate
  ) |>
  select(
    TeamName, opponent, location, Season, diff_eFGPct, diff_TOPct, diff_ORPct, diff_FTRate
  )|>
  relocate(TeamName, opponent, Season) |>
  mutate(home = if_else(location == "N", 0, 1))
```

```{r}
merged_all_2026_pred <- merged_all_2026 |>
  mutate(predicted = predict(model_1, newdata = merged_all_2026))
```










```{r}
stats_2026 <- acc_teams_stats |>
  filter(Season == 2026)

predict <- predict |>
  select(Away, Home) |>
  rename(
    "TeamName" = "Home",
    "opponent" = "Away"
  )

left_join(
  predict,
  stats_2026,
  by = "TeamName"
) |>
  drop_na() |>
  rename("home_eFGPct" = "eFGPct",
         "home_TOPct" = "TOPct",
         "home_ORPct" = "ORPct",
         "home_FTRate" = "FTRate",
         "opponent" = "opponent.x"
  )
```

